name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2  # ✅ Latest stable 4.x release  [oai_citation:0‡Release Alert](https://releasealert.dev/github/actions/checkout?utm_source=chatgpt.com)

    - name: Setup Node.js
      uses: actions/setup-node@v4  # v4 is current major release

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v4  # Matches deploy artifact flow

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3  # Required by deploy-pages@v4 ()
      with:
        path: _site

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v4  # v4 required, works with upload-pages-artifact@v3 ()

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false