
name: Update Schedules

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Fetch and update data
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Fetch and update data
        run: node scripts/update-f1-schedule.js && node scripts/update-nascar-schedule.js && python scripts/update-indycar-schedule.py && node scripts/update-f1-results.js && node scripts/update-indycar-results.js && node scripts/update-nascar-results.js && node scripts/consolidate-data.js && node scripts/update-standings.js

      - name: Build Eleventy site
        run: npm run build

      - name: Commit and push data changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated data update'
          file_pattern: '**/*'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
